apiVersion: v1
appVersion: "1.0"
description: A Helm chart for demo app named Echo FE
name: echofe
version: 0.1.0
appVersion: 1.0
maintainers:
  - name: Tiran Meltser
    email: tiran.meltser@mavenir.com